### ISSUE TITLE
project-level build.gradle file is where repositories are designated, whereas module:app build.gradle file is where packages are compiled

### ISSUE THREAD

**Issue by Atticus29** [safetysystemtechnology/location-tracker-background#11]
I can't seem to correctly configure the gradle file per the README in my Android project. I keep getting the following Error: "Failed to resolve: com.github.safetysystemtechnology:location-tracker-background:v1.2". I tried adding the maven repository the project-level build.gradle file and the dependency to the Module:app-level build.gradle file. Same error. Apologies for the newbie question.

**Comment by netodevel** [comment]
> please use version 1.3, it contains fixes.

**in your module (: project)**
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**in your module (: app)**

```
dependencies {
  ...
  compile 'com.github.safetysystemtechnology:location-tracker-background:v1.3'
}
```
