### ISSUE TITLE
Stop Service

### ISSUE THREAD

**Issue by daupawar** [safetysystemtechnology/location-tracker-background#3]
How i can stop the started location service?

**Comment by netodevel** [comment]
Sorry for the delay, there is no really a stop method: / I will be releasing a version of the library with some interesting features such as smart gps. I will include the stop method.

**Comment by daupawar** [comment]
Thank for the reply

**Comment by ganeshachar** [comment]
hi,
How i can stop the started location service? can you provide me stop method

**Comment by daupawar** [comment]
There is no method available right now to stop service @NetoDevel will be releasing with this feature
but you can your stop service like this

 ```
 Intent serviceIntent = new Intent(context, LocationService.class);
 context.stopService(serviceIntent);
```

**Comment by ganeshachar** [comment]
Thank you for the quick response,its working for me
awesome tutorial, working perfectly no issues thank you

**Comment by netodevel** [comment]
@daupawar Thanks for the stop method, could you make a pull request? While I'm working on new features?

**Comment by daupawar** [comment]
@NetoDevel Sure

**Comment by ganeshachar** [comment]
hi, in this app service calling first time twice in fraction of seconds,(while app open time) ,how to solve this,can you help me pls.
Location:: Latitude: 12.9244812Longitude:77.6197381
Location:: Latitude: 12.9244812Longitude:77.6197381

**Comment by netodevel** [comment]
@ganeshachar show me your build of object LocationTracker and your code of broadcast receiver

**Comment by ganeshachar** [comment]
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
//apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
   /* useLibrary 'org.apache.http.legacy'*/
    defaultConfig {
        applicationId "com.alive911"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
   /* packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
    }*/
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:percent:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services:10.0.1'
    compile 'com.android.support:cardview-v7:25.2.0'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.google.android.gms:play-services-auth:10.0.1'
    compile 'com.google.firebase:firebase-appindexing:10.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.kayvannj:PermissionUtils:1.0.2@aar'
    compile 'com.android.support:multidex:1.0.1'
   /* compile 'org.apache.httpcomponents:httpcore:4.4'
    compile 'org.apache.httpcomponents:httpmime:4.4'*/
    testCompile 'junit:junit:4.12'
    compile('com.twitter.sdk.android:twitter:2.3.2@aar') {
        transitive = true;
    }

    }
apply plugin: 'com.google.gms.google-services'

**Comment by ganeshachar** [comment]
this is receiver

**Comment by ganeshachar** [comment]
```
public class LocationReceiver extends BroadcastReceiver {
    Context context;
    String locat1;
    MediaPlayer mPlayer2;
    @Override
    public void onReceive(Context context, Intent intent) {
        if (null != intent && intent.getAction().equals("my.action")) {
            Location locationData = (Location) intent.getParcelableExtra(SettingsLocationTracker.LOCATION_MESSAGE);
            Log.d("Location: ", "Latitude: " + locationData.getLatitude() + "Longitude:" + locationData.getLongitude());
            Toast.makeText(context,"Location"+"Latitude: " + locationData.getLatitude() + "Longitude:" + locationData.getLongitude(),Toast.LENGTH_LONG).show();
            locat1 = "{"+locationData.getLatitude() + "," + locationData.getLongitude()+"}";

            if (!Utils.isOnline(context)) {
                Toast.makeText(context, "check your internet connection", Toast.LENGTH_LONG).show();
                Intent i = new Intent(context,NoInternetAlert.class);
                i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                context.startActivity(i);
            } else {
                TrackMeApiClass.trackMeApi(locat1, context, mPlayer2);
            }

        }
    }

}
```

**Comment by ganeshachar** [comment]
```
  imageTrackme1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!Utils.isOnline(EmergencyAlaramActivity.this)) {
                    Toast.makeText(EmergencyAlaramActivity.this, "check your internet connection", Toast.LENGTH_LONG).show();
                } else {
                    new LocationTracker("my.action")
                            .setInterval(600000)
                            //.setInterval(10000)
                            .setGps(true)
                            .setNetWork(false)
                            .start(getBaseContext(), EmergencyAlaramActivity.this);

                }
            }
        });
```

**Comment by daupawar** [comment]
`LocationReceiver` calls when `onLocationChanged` triggered,
`onLocationChanged`  triggers when

-  device moves in particular area(distance in meter)
-  specific time
-  GPS on/off

lib cant handle `onLocationChanged` event .

Note:-
@ganeshachar `LocationReceiver` can call multiple time in single minute (depends on interval you have set), as per my opinion don't start any new intent inside `BroadcastReceiver`. it can cause to multiple intent stack of same activity
