### ISSUE TITLE
Location Service Make Crash

### ISSUE THREAD

**Issue by ntancnit** [safetysystemtechnology/location-tracker-background#4]
Hi I found this issue : 

![screen shot 2017-06-16 at 11 27 41 am](https://user-images.githubusercontent.com/3159750/27211936-e01de046-5286-11e7-81d1-07d0a8f4add7.png)
![screen shot 2017-06-16 at 11 27 26 am](https://user-images.githubusercontent.com/3159750/27211941-e85da30e-5286-11e7-9561-7cb1e0355724.png)

**Comment by netodevel** [comment]
@ntancnit update to version v1.1, i fixed the bug.

```
dependencies {
    compile 'com.github.safetysystemtechnology:location-tracker-background:v1.1'
}
```
