### ISSUE TITLE
app_name present in library's AndroidManifest

### ISSUE THREAD

**Issue by SylvainGirod** [safetysystemtechnology/location-tracker-background#8]
Hi !
I'm having trouble with the AndroidManifest.xml file which is present in the library.
It seems to have it's own label, and so, I can't set mine in my app's manifest.
I've got this error when building :
`Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : Attribute application@label value=(Urbee) from AndroidManifest.xml:35:9-30
	is also present at [com.github.safetysystemtechnology:location-tracker-background:v1.2] AndroidManifest.xml:16:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:32:5-109:19 to override.`

**Comment by netodevel** [comment]
is a very strange error .. happens when you run or build the application?

**Comment by SylvainGirod** [comment]
It happened on build.
I made a PR, but I think I failed the reference on it (new to this, very sorry)

**Comment by netodevel** [comment]
is strange because it does not happen in my application, and all my libs have app name and this problem does not happen. I think it's in your manifest of your application.

**Comment by netodevel** [comment]
try add `multidex` to your `build.gradle`:
https://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library

**Comment by SylvainGirod** [comment]
It works now ! Thanks !
MultiDex was not the solution, I had to replace your label by mine (as suggested by the error, but it didn't work at first try...)
